Repository healthHealther/healthHealtherBE, pull requests merged in 2023-01, with the labels that each got.

#21 [#20] feat: Entity 설계
  src/main/java/com/health/healther/constant/ConvenienceType.java
  src/main/java/com/health/healther/constant/LoginType.java
  src/main/java/com/health/healther/constant/MemberStatus.java
  src/main/java/com/health/healther/domain/model/BaseEntity.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/domain/model/BoardLike.java
  src/main/java/com/health/healther/domain/model/Comment.java
  src/main/java/com/health/healther/domain/model/Convenience.java
  src/main/java/com/health/healther/domain/model/Coupon.java
  src/main/java/com/health/healther/domain/model/Image.java
  src/main/java/com/health/healther/domain/model/Member.java
  src/main/java/com/health/healther/domain/model/Reservation.java
  src/main/java/com/health/healther/domain/model/Review.java
  src/main/java/com/health/healther/domain/model/Space.java
  src/main/java/com/health/healther/domain/model/SpaceTime.java
  src/main/java/com/health/healther/domain/model/SpaceType.java
  src/main/java/com/health/healther/domain/repository/BoardLikeRepository.java
  src/main/java/com/health/healther/domain/repository/BoardRepository.java
  src/main/java/com/health/healther/domain/repository/CommentRepository.java
  src/main/java/com/health/healther/domain/repository/ConvenienceRepository.java
  src/main/java/com/health/healther/domain/repository/CouponRepository.java
  src/main/java/com/health/healther/domain/repository/ImageRepository.java
  src/main/java/com/health/healther/domain/repository/MemberRepository.java
  src/main/java/com/health/healther/domain/repository/ReservationRepository.java
  src/main/java/com/health/healther/domain/repository/ReviewRepository.java
  src/main/java/com/health/healther/domain/repository/SpaceRepository.java
  src/main/java/com/health/healther/domain/repository/SpaceTimeRepository.java
  src/main/java/com/health/healther/domain/repository/SpaceTypeRepository.java
Labels: 💪 enhancement

#23 [#22] yml profile에 따라 분리
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 👷‍♀️ chore

#25 [#24] 자동리뷰어와 PR 템플릿 설정
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: 👷‍♀️ chore

#30 [#29] local에서 h2 DB 활성화, redis profile 제거, EnableJpaAuditing 설정 추가
  src/main/java/com/health/healther/HealtherApplication.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 👷‍♀️ chore

#31 [#27] 공간 등록 API
  build.gradle
  src/main/java/com/health/healther/constant/SpaceType.java
  src/main/java/com/health/healther/controller/SpaceController.java
  src/main/java/com/health/healther/domain/model/Convenience.java
  src/main/java/com/health/healther/domain/model/Image.java
  src/main/java/com/health/healther/domain/model/Space.java
  src/main/java/com/health/healther/domain/model/SpaceKind.java
  src/main/java/com/health/healther/domain/model/SpaceTime.java
  src/main/java/com/health/healther/domain/repository/SpaceKindRepository.java
  src/main/java/com/health/healther/domain/repository/SpaceTypeRepository.java
  src/main/java/com/health/healther/dto/space/ConvenienceTypeDto.java
  src/main/java/com/health/healther/dto/space/CreateSpaceRequestDto.java
  src/main/java/com/health/healther/dto/space/ImageUrlDto.java
  src/main/java/com/health/healther/dto/space/SpaceTypeDto.java
  src/main/java/com/health/healther/exception/ErrorMessage.java
  src/main/java/com/health/healther/exception/space/NotMatchConvenienceTypeException.java
  src/main/java/com/health/healther/exception/space/NotMatchSpaceTypeException.java
  src/main/java/com/health/healther/exception/space/SpaceExceptionHandler.java
  src/main/java/com/health/healther/service/SpaceService.java
Labels: 💪 enhancement

#38 [#37] Security Config 및 JwtAuthenticationFilter 추가
  src/main/java/com/health/healther/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/health/healther/config/JwtAuthenticationFilter.java
  src/main/java/com/health/healther/config/SecurityConfig.java
  src/main/java/com/health/healther/controller/OauthController.java
  src/main/java/com/health/healther/domain/model/Member.java
  src/main/java/com/health/healther/exception/member/SendErrorResponse.java
  src/main/java/com/health/healther/service/AuthService.java
  src/main/java/com/health/healther/service/MemberService.java
  src/main/java/com/health/healther/service/OauthService.java
  src/main/java/com/health/healther/util/SecurityUtil.java
  src/main/java/com/health/healther/util/UserAuthentication.java
Labels: 💪 enhancement

#41 [#39] 회원정보 수정 API
  src/main/java/com/health/healther/controller/MemberController.java
  src/main/java/com/health/healther/dto/member/MemberDto.java
  src/main/java/com/health/healther/service/MemberService.java
Labels: 💪 enhancement

#34 [#32] 회원가입 / 로그인 Kakao
  build.gradle
  src/main/java/com/health/healther/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/health/healther/config/JwtAuthenticationFilter.java
  src/main/java/com/health/healther/config/JwtConfig.java
  src/main/java/com/health/healther/config/JwtTokenProvider.java
  src/main/java/com/health/healther/config/SecurityConfig.java
  src/main/java/com/health/healther/controller/MemberController.java
  src/main/java/com/health/healther/controller/OauthController.java
  src/main/java/com/health/healther/domain/model/Member.java
  src/main/java/com/health/healther/domain/repository/MemberRepository.java
  src/main/java/com/health/healther/dto/member/LoginResponse.java
  src/main/java/com/health/healther/dto/member/MemberDto.java
  src/main/java/com/health/healther/dto/member/OauthTokenResponse.java
  src/main/java/com/health/healther/dto/member/SignUpForm.java
  src/main/java/com/health/healther/dto/member/userInfo/KakaoUserInfo.java
  src/main/java/com/health/healther/dto/member/userInfo/OAuth2UserInfo.java
  src/main/java/com/health/healther/exception/member/MemberCustomException.java
  src/main/java/com/health/healther/exception/member/MemberErrorCode.java
  src/main/java/com/health/healther/exception/member/MemberErrorResponse.java
  src/main/java/com/health/healther/exception/member/MemberExceptionHandler.java
  src/main/java/com/health/healther/exception/member/SendErrorResponse.java
  src/main/java/com/health/healther/service/AuthService.java
  src/main/java/com/health/healther/service/MemberService.java
  src/main/java/com/health/healther/service/OauthService.java
  src/main/java/com/health/healther/util/SecurityUtil.java
  src/main/java/com/health/healther/util/UserAuthentication.java
  src/main/resources/application-oauth.yml
Labels: 💪 enhancement, 👩‍🔧 refactor

#57 [#56] 회원가입 / 로그인 API (Google)
  src/main/java/com/health/healther/controller/OauthController.java
  src/main/java/com/health/healther/dto/member/LoginResponse.java
  src/main/java/com/health/healther/dto/member/userInfo/GoogleUserInfo.java
  src/main/java/com/health/healther/service/OauthService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-prod.yml
Labels: 💪 enhancement

#65 [#63] 쿠폰 조회 API
  src/main/java/com/health/healther/controller/CouponController.java
  src/main/java/com/health/healther/domain/repository/CouponRepository.java
  src/main/java/com/health/healther/dto/coupon/CouponResponseDto.java
  src/main/java/com/health/healther/service/CouponService.java
Labels: 💪 enhancement

#68 [#64] 쿠폰 수정 API
  src/main/java/com/health/healther/controller/CouponController.java
  src/main/java/com/health/healther/domain/model/Coupon.java
  src/main/java/com/health/healther/domain/repository/CouponRepository.java
  src/main/java/com/health/healther/dto/coupon/CouponUpdateRequestDto.java
  src/main/java/com/health/healther/exception/coupon/CouponExceptionHandler.java
  src/main/java/com/health/healther/service/CouponService.java
Labels: 💪 enhancement

#82 [#81] 전체 코드 리팩토링
  src/main/java/com/health/healther/config/SecurityConfig.java
  src/main/java/com/health/healther/controller/CouponController.java
  src/main/java/com/health/healther/controller/MemberController.java
  src/main/java/com/health/healther/controller/OauthController.java
  src/main/java/com/health/healther/controller/ReviewController.java
  src/main/java/com/health/healther/controller/SpaceController.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/domain/model/BoardLike.java
  src/main/java/com/health/healther/domain/model/Comment.java
  src/main/java/com/health/healther/domain/model/Reservation.java
  src/main/java/com/health/healther/domain/model/SpaceTime.java
  src/main/java/com/health/healther/domain/repository/CouponRepository.java
  src/main/java/com/health/healther/dto/coupon/CouponCreateRequestDto.java
  src/main/java/com/health/healther/dto/coupon/CouponResponseDto.java
  src/main/java/com/health/healther/dto/coupon/CouponUpdateRequestDto.java
  src/main/java/com/health/healther/dto/member/MemberDto.java
  src/main/java/com/health/healther/dto/review/ReviewDto.java
  src/main/java/com/health/healther/dto/review/ReviewRequestUpdateDto.java
  src/main/java/com/health/healther/dto/space/SpaceListRequestDto.java
  src/main/java/com/health/healther/exception/review/NoFoundMemberException.java
  src/main/java/com/health/healther/exception/review/NoFoundReviewException.java
  src/main/java/com/health/healther/exception/review/NoFoundSpaceException.java
  src/main/java/com/health/healther/exception/review/NotFoundMemberException.java
  src/main/java/com/health/healther/exception/review/NotFoundReviewException.java
  src/main/java/com/health/healther/exception/review/ReviewExceptionHandler.java
  src/main/java/com/health/healther/review/exception/ErrorMessage.java
  src/main/java/com/health/healther/service/CouponService.java
  src/main/java/com/health/healther/service/MemberService.java
  src/main/java/com/health/healther/service/ReviewService.java
Labels: 👩‍🔧 refactor

#86 [#83] Member/로그인 관련 리팩토링
  src/main/java/com/health/healther/config/JwtAccessDeniedHandler.java
  src/main/java/com/health/healther/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/health/healther/config/JwtAuthenticationFilter.java
  src/main/java/com/health/healther/config/SecurityConfig.java
  src/main/java/com/health/healther/controller/MemberController.java
  src/main/java/com/health/healther/controller/OauthController.java
  src/main/java/com/health/healther/dto/member/MemberLoginResponseDto.java
  src/main/java/com/health/healther/dto/member/MemberOauthResponseDto.java
  src/main/java/com/health/healther/dto/member/MemberSearchResponseDto.java
  src/main/java/com/health/healther/dto/member/MemberSignUpRequestDto.java
  src/main/java/com/health/healther/dto/member/MemberUpdateRequestDto.java
  src/main/java/com/health/healther/dto/member/OauthTokenResponseDto.java
  src/main/java/com/health/healther/dto/member/userInfo/GoogleUserInfo.java
  src/main/java/com/health/healther/dto/member/userInfo/KakaoUserInfo.java
  src/main/java/com/health/healther/exception/member/InvalidAccessException.java
  src/main/java/com/health/healther/exception/member/InvalidTokenException.java
  src/main/java/com/health/healther/exception/member/MemberCustomException.java
  src/main/java/com/health/healther/exception/member/MemberErrorCode.java
  src/main/java/com/health/healther/exception/member/MemberErrorResponse.java
  src/main/java/com/health/healther/exception/member/MemberExceptionHandler.java
  src/main/java/com/health/healther/exception/member/NotFoundMemberException.java
  src/main/java/com/health/healther/exception/member/NotMatchMemberException.java
  src/main/java/com/health/healther/exception/member/SendErrorResponse.java
  src/main/java/com/health/healther/service/AuthService.java
  src/main/java/com/health/healther/service/MemberService.java
  src/main/java/com/health/healther/service/OauthService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 👩‍🔧 refactor

#85 [#84] CouponExceptionHandler 리팩토링
  src/main/java/com/health/healther/exception/coupon/CouponExceptionHandler.java
  src/main/java/com/health/healther/exception/coupon/NotFoundCouponException.java
  src/main/java/com/health/healther/service/CouponService.java
Labels: 👩‍🔧 refactor

#90 [#89] mac환경 webFlux 오류 해결 및 Jwt토큰 유무에 따른 예외생성
  build.gradle
  src/main/java/com/health/healther/config/JwtAccessDeniedHandler.java
  src/main/java/com/health/healther/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/health/healther/config/JwtAuthenticationFilter.java
  src/main/java/com/health/healther/config/JwtTokenProvider.java
  src/main/java/com/health/healther/config/SecurityConfig.java
  src/main/java/com/health/healther/controller/MemberController.java
  src/main/java/com/health/healther/exception/member/ForbiddenMemberException.java
  src/main/java/com/health/healther/exception/member/UnauthorizedMemberException.java
  src/main/java/com/health/healther/util/UserAuthentication.java
Labels: 🐞 bug, ⚒️ fix, 👩‍🔧 refactor

#80 [#71] 공간 예약 추가 API
  src/main/java/com/health/healther/controller/ReservationController.java
  src/main/java/com/health/healther/domain/model/Reservation.java
  src/main/java/com/health/healther/domain/repository/ReservationRepository.java
  src/main/java/com/health/healther/dto/reservation/AvailableTimeResponseDto.java
  src/main/java/com/health/healther/dto/reservation/MakeReservationRequestDto.java
  src/main/java/com/health/healther/exception/reservation/AlreadyReservedException.java
  src/main/java/com/health/healther/exception/reservation/InappropriateDateException.java
  src/main/java/com/health/healther/exception/reservation/NotBusinessHoursException.java
  src/main/java/com/health/healther/exception/reservation/ReservationExceptionHandler.java
  src/main/java/com/health/healther/service/ReservationService.java
Labels: 💪 enhancement

#101 [#100] 게시판 상세조회 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/dto/board/BoardDetailResponseDto.java
  src/main/java/com/health/healther/exception/board/BoardExceptionHandler.java
  src/main/java/com/health/healther/exception/board/NotFoundBoardException.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#88 [#87] 쿠폰 조회 리팩토링
  src/main/java/com/health/healther/controller/CouponController.java
  src/main/java/com/health/healther/domain/repository/CouponRepository.java
  src/main/java/com/health/healther/dto/coupon/CouponReservationListResponseDto.java
  src/main/java/com/health/healther/service/CouponService.java
Labels: 👩‍🔧 refactor

#97 [#96] mysql에서 mariadb로 변경
  build.gradle
  src/main/resources/application-datasource.yml
Labels: 👷‍♀️ chore

#108 [#107] Cors 관련 설정 추가
  src/main/java/com/health/healther/config/WebMvcConfig.java
Labels: 💪 enhancement

#109 [#103] 쿠폰 등록 리팩토링
  src/main/java/com/health/healther/controller/CouponController.java
  src/main/java/com/health/healther/domain/model/Coupon.java
  src/main/java/com/health/healther/exception/coupon/CouponCustomException.java
  src/main/java/com/health/healther/exception/coupon/CouponErrorCode.java
  src/main/java/com/health/healther/service/CouponService.java
Labels: 👩‍🔧 refactor

#93 [#92] 예약 조회 기능 API
  src/main/java/com/health/healther/controller/ReservationController.java
  src/main/java/com/health/healther/domain/repository/ReservationRepository.java
  src/main/java/com/health/healther/dto/reservation/ReservationListResponseDto.java
  src/main/java/com/health/healther/exception/reservation/ReservationExceptionHandler.java
  src/main/java/com/health/healther/service/ReservationService.java
Labels: 💪 enhancement

#112 [#111] 예약 관련 쿠폰 처리 로직 생성
  src/main/java/com/health/healther/domain/model/Coupon.java
  src/main/java/com/health/healther/service/CouponService.java
Labels: 💪 enhancement

#99 [#98] 게시판 등록 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/domain/model/Comment.java
  src/main/java/com/health/healther/dto/board/BoardCreateRequestDto.java
  src/main/java/com/health/healther/dto/board/BoardDetailResponseDto.java
  src/main/java/com/health/healther/exception/board/BoardExceptionHandler.java
  src/main/java/com/health/healther/exception/board/NotFoundBoardException.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#127 [#126] Space Service 코드에 Member 연결
  src/main/java/com/health/healther/domain/model/Space.java
  src/main/java/com/health/healther/dto/space/SpaceDetailResponseDto.java
  src/main/java/com/health/healther/service/SpaceService.java
Labels: 👩‍🔧 refactor

#116 [#115] 게시글 수정 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/dto/board/BoardUpdateRequestDto.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#114 [#102] 게시판 삭제 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#118 [#117] 게시글 추천 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/domain/repository/BoardLikeRepository.java
  src/main/java/com/health/healther/exception/board/BoardExceptionHandler.java
  src/main/java/com/health/healther/exception/board/BoardLikeAlreadyExistException.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#131 [#130] redis 설정 및 refreshToken 관련 리팩토링
  build.gradle
  src/main/java/com/health/healther/config/RedisConfig.java
  src/main/java/com/health/healther/config/RedisProperties.java
  src/main/java/com/health/healther/controller/MemberController.java
  src/main/java/com/health/healther/dto/member/AccessTokenResponseDto.java
  src/main/java/com/health/healther/dto/member/MemberLoginResponseDto.java
  src/main/java/com/health/healther/service/AuthService.java
  src/main/java/com/health/healther/service/OauthService.java
  src/main/java/com/health/healther/util/AuthTransformUtil.java
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
Labels: 👩‍🔧 refactor

#120 [#119] 게시판 추천 취소 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/exception/board/BoardExceptionHandler.java
  src/main/java/com/health/healther/exception/board/NotFoundBoardLikeException.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#122 [#121] 게시판 본인 추천 여부 조회 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/dto/board/BoardIsLikedResponseDto.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#128 [#125] 예약 취소 시 쿠폰 사용 취소 로직 생성
  src/main/java/com/health/healther/exception/coupon/CouponExceptionHandler.java
  src/main/java/com/health/healther/exception/coupon/NotUsedCouponException.java
  src/main/java/com/health/healther/service/CouponService.java
Labels: 💪 enhancement

#138 [#137] 테이블 생성 시 테이블명 모두 대문자로 변경
  src/main/java/com/health/healther/config/UpperCaseNamingStrategy.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 🐞 bug

#136 [#132] 예약 추가/삭제에 쿠폰 사용/복원 반영
  src/main/java/com/health/healther/service/ReservationService.java
Labels: 👩‍🔧 refactor

#141 [#140] 로그인 후 expiredTime 응답값 변경
  src/main/java/com/health/healther/dto/member/AccessTokenResponseDto.java
  src/main/java/com/health/healther/dto/member/MemberLoginResponseDto.java
  src/main/java/com/health/healther/service/AuthService.java
  src/main/java/com/health/healther/service/OauthService.java
Labels: 👩‍🔧 refactor

#147 [#146] 98 branch merge 오류 수정
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 🐞 bug

#149 게시글 수정 리팩토링
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 🐞 bug

#139 [#129] 쿠폰 다운 API
  src/main/java/com/health/healther/controller/CouponController.java
  src/main/java/com/health/healther/domain/model/Coupon.java
  src/main/java/com/health/healther/domain/repository/CouponRepository.java
  src/main/java/com/health/healther/exception/coupon/AlreadyDownloadCouponException.java
  src/main/java/com/health/healther/exception/coupon/AlreadySoldOutCouponException.java
  src/main/java/com/health/healther/exception/coupon/CouponExceptionHandler.java
  src/main/java/com/health/healther/service/CouponService.java
Labels: 💪 enhancement

#155 [#154] 공간 등록 시 쿠폰 등록 같이 하도록 변경
  src/main/java/com/health/healther/dto/coupon/CouponCreateRequestDto.java
  src/main/java/com/health/healther/dto/space/CreateSpaceRequestDto.java
  src/main/java/com/health/healther/service/SpaceService.java
Labels: 💪 enhancement

#145 [#144] 예약 API 쿠폰 여부에 따른 분기 순서 변경
  src/main/java/com/health/healther/service/ReservationService.java
Labels: 👩‍🔧 refactor

#153 [#152] 게시판 조회 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/model/Board.java
  src/main/java/com/health/healther/domain/repository/BoardRepository.java
  src/main/java/com/health/healther/dto/board/GetBoardListRequestDto.java
  src/main/java/com/health/healther/dto/board/GetBoardListResponseDto.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#161 [#156] 공간 리스트 조회 리팩토링
  src/main/java/com/health/healther/config/SecurityConfig.java
  src/main/java/com/health/healther/constant/SpaceType.java
  src/main/java/com/health/healther/domain/repository/CouponRepository.java
  src/main/java/com/health/healther/domain/repository/ReviewRepository.java
  src/main/java/com/health/healther/domain/repository/SpaceKindRepository.java
  src/main/java/com/health/healther/dto/space/SpaceListResponseDto.java
  src/main/java/com/health/healther/service/CouponService.java
  src/main/java/com/health/healther/service/SpaceService.java
Labels: 👩‍🔧 refactor

#157 [#135] 게시판 댓글 조회 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/repository/CommentRepository.java
  src/main/java/com/health/healther/dto/board/CommentListRequestDto.java
  src/main/java/com/health/healther/dto/board/CommentListResponseDto.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#162 [#156] OptionalDouble import문 추가
  src/main/java/com/health/healther/dto/space/SpaceListResponseDto.java
Labels: 🐞 bug

#164 [#158]게시글 댓글 수정 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/model/Comment.java
  src/main/java/com/health/healther/dto/board/CommentUpdateRequestDto.java
  src/main/java/com/health/healther/exception/board/BoardExceptionHandler.java
  src/main/java/com/health/healther/exception/board/NotFoundBoardException.java
  src/main/java/com/health/healther/exception/board/NotFoundCommentException.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#166 [#165] 게시글 추천/ 추천 취소 API 리팩토링
  src/main/java/com/health/healther/domain/model/BoardLike.java
  src/main/java/com/health/healther/exception/board/AlreadyBoardLikeException.java
  src/main/java/com/health/healther/exception/board/BoardExceptionHandler.java
  src/main/java/com/health/healther/exception/board/BoardLikeAlreadyExistException.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 👩‍🔧 refactor

#168 [#167] 게시글 조회 관련 리팩토링
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 👩‍🔧 refactor

#174 [#173] 공간 리스트 조회 버그 수정
  src/main/java/com/health/healther/dto/space/SpaceListResponseDto.java
  src/main/java/com/health/healther/service/SpaceService.java
Labels: 🐞 bug

#171 [#169]게시글 추천수 조회 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/dto/board/GetBoardLikeCountResponseDto.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#170 [#163] 게시글 타이틀 검색 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/domain/repository/BoardRepository.java
  src/main/java/com/health/healther/dto/board/BoardSearchListRequestDto.java
  src/main/java/com/health/healther/dto/board/BoardSearchListResponseDto.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#175 [#172] 게시글 댓글 삭제 API
  src/main/java/com/health/healther/controller/BoardController.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 💪 enhancement

#177 [#176] 추천 취소 버그 수정
  src/main/java/com/health/healther/exception/board/AlreadyBoardLikeException.java
  src/main/java/com/health/healther/exception/board/AlreadyDeleteBoardLikeException.java
  src/main/java/com/health/healther/exception/board/BoardExceptionHandler.java
  src/main/java/com/health/healther/service/BoardService.java
Labels: 🐞 bug

#178 [#160] 후기(Review) 등록 리팩토링 및 테스트
  src/main/java/com/health/healther/controller/ReviewController.java
  src/main/java/com/health/healther/domain/model/Review.java
  src/main/java/com/health/healther/domain/repository/ReviewRepository.java
  src/main/java/com/health/healther/dto/review/ReviewCreateRequestDto.java
  src/main/java/com/health/healther/exception/review/AlreadyCreateReviewException.java
  src/main/java/com/health/healther/exception/review/ReviewExceptionHandler.java
  src/main/java/com/health/healther/service/ReviewService.java
Labels: 🐞 bug, 🧪 test, 👩‍🔧 refactor

#180 [#179] CORS 설정 내 'OPTIONS' 메서드 허가
  src/main/java/com/health/healther/config/JwtAuthenticationFilter.java
  src/main/java/com/health/healther/config/WebMvcConfig.java
Labels: 🐞 bug
