Repository healthHealther/healthHealtherBE, pull requests merged in 2023-02, with the labels that each got.

#182 [#181] 쿠폰 관련 requestDto LocalDate를 String으로 데이터 타입 변경 리팩토링
  src/main/java/com/health/healther/domain/model/Coupon.java
  src/main/java/com/health/healther/dto/coupon/CouponCreateRequestDto.java
  src/main/java/com/health/healther/dto/coupon/CouponUpdateRequestDto.java
  src/main/java/com/health/healther/dto/space/CreateSpaceRequestDto.java
  src/main/java/com/health/healther/service/CouponService.java
  src/main/java/com/health/healther/util/DateTimeUtil.java
Labels: ⚒️ fix, 👩‍🔧 refactor

#185 [#184] 후기 조회 리팩토링
  src/main/java/com/health/healther/controller/ReviewController.java
  src/main/java/com/health/healther/domain/repository/ReviewRepository.java
  src/main/java/com/health/healther/dto/review/ReviewCreateRequestDto.java
  src/main/java/com/health/healther/dto/review/ReviewRequestUpdateDto.java
  src/main/java/com/health/healther/service/ReviewService.java
Labels: 👩‍🔧 refactor

#187 [#186] 쿠폰 다운 API 반환값 추가 리팩토링
  src/main/java/com/health/healther/controller/CouponController.java
  src/main/java/com/health/healther/domain/repository/CouponRepository.java
  src/main/java/com/health/healther/dto/coupon/CouponDownLoadResponseDto.java
  src/main/java/com/health/healther/service/CouponService.java
Labels: 💪 enhancement, 👩‍🔧 refactor

#189 [#188] oauth-application 내 redirect_uri 환경변수 수정
  src/main/resources/application-oauth.yml
Labels: 🐞 bug
